### ISSUE TITLE
pyerr_fetch

### ISSUE THREAD

**Issue by vmtest888** [TimWhiting/dartpy#11]
When an error occurs, use pyerr_ Fetch obtains information and then throws an exception through Dart to make the error more clear

**Comment by TimWhiting** [comment]
You are welcome to create a pull request, seems like you know what to do.

**Comment by vmtest888** [comment]
Another suggestion is that different systems have different ABIs. For example, the wchar in py_setpath is int32 on macos and int16 on windows. We hope to automatically match and convert it from the string type in dart to the corresponding platform type·
