### ISSUE TITLE
flutter: DartPyException(Importing python module namefinder failed, make sure the namefinder is on your PYTHONPATH  eg. export PYTHONPATH=$PYTHONPATH:/path/to/namefinder)

### ISSUE THREAD

**Issue by rhiotbdq** [TimWhiting/dartpy#3]
I have been trying to build a model in python and put that in dart using this library. However, I keep on getting this same error. Can you please walk me through how to set this up such that I can actually run my python function on dart, set up my PYTHONPATH because I am very confused. Thank you so much!

**Comment by TimWhiting** [comment]
Sounds like you are having trouble with setting up your PYTHONPATH. Make sure it has your python scripts in the path.
Duplicate of #2
